"""
PROBLEM 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def main():

    a = 1
    b = 2
    c = 0
    even_sum = 2

    while c < 4_000_000:
        # add previous two numbers
        c = a + b

        # add to sum if even
        if c % 2 == 0:
            even_sum += c

        # assign c to a or b
        if a < b:
            a = c
        else:
            b = c

    print(even_sum)


if __name__ == "__main__":
    main()
